### ISSUE TITLE
Undefined chili element

### ISSUE THREAD

**Issue by yehya** [yehya/rmp-api#1]
`rmp.get("Timothy Purnell", callback);`

causes

`TypeError: Cannot read property 'replace' of undefined`

on line 138 of src/main.js

**Comment by yehya** [comment]
Hotfixed [here](https://github.com/awadYehya/rmp-api/commit/a868f029b0406bc285bf0885feadf316b3942687)

Still not clear on how this error happens

**Comment by kennethgoodman** [comment]
var BC = rmp("Baruch College")
BC.get("Sunil Nair", callback)
[Error: Chili undefined. This is a rare error that happens for a few professors. Please help us out by providing the query you used with rmp-api.]
http://www.ratemyprofessors.com/AddRating.jsp?tid=2110884
Maybe because the teacher has no data, just a page?

**Comment by yehya** [comment]
Thanks for the feedback @kennethgoodman - that was indeed the problem.
